name: UM
version: '0.1.0.0'
category: VM
author: Jon Distad
maintainer: jon.distad@gmail.com
copyright: 2017 Jon Distad
license: BSD3
github: jondistad/um

library:
  source-dirs: src
  dependencies:
    - array
    - base >=4.7 && <5
    - base-prelude
    - bytestring
    - lens
    - mtl
    - transformers
  default-extensions:
    - ConstraintKinds
    - FlexibleInstances
    - FlexibleContexts
    - FunctionalDependencies
    - MultiParamTypeClasses
    - NamedFieldPuns
    - NoImplicitPrelude
    - RankNTypes
    - ScopedTypeVariables
    - Strict
    - ViewPatterns

executables:
  UM:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -O
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N1
    dependencies:
      - base
      - UM

tests:
  UM-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N1
    dependencies:
      - base
      - UM
